title: Zecheng Hao | Homepage
description: Studying at National Engineering Research Center of Visual Technology, Peking University. Focusing on visual information processing and brain like intelligence.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
dblp-url: https://dblp.org/pid/339/6969.html
github-url: https://github.com/hzc1208
google-scholar: https://scholar.google.com/citations?user=txTkX7YAAAAJ
orcid-url: https://orcid.org/0000-0001-9074-2857
researchgate-url: https://www.researchgate.net/profile/Zecheng-Hao/research
